/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutCourseIdRouteImport } from './routes/checkout.$courseId'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppTeacherRouteImport } from './routes/_authenticated/app/teacher'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/app/library'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app/community'
import { Route as AuthenticatedAppClinicalCasesRouteImport } from './routes/_authenticated/app/clinical-cases'
import { Route as AuthenticatedAppAiTutorRouteImport } from './routes/_authenticated/app/ai-tutor'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppAchievementsRouteImport } from './routes/_authenticated/app/achievements'
import { Route as AuthenticatedAppCoursesIndexRouteImport } from './routes/_authenticated/app/courses.index'
import { Route as AuthenticatedAppLessonsLessonIdRouteImport } from './routes/_authenticated/app/lessons.$lessonId'
import { Route as AuthenticatedAppCoursesCourseIdRouteImport } from './routes/_authenticated/app/courses.$courseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCourseIdRoute = CheckoutCourseIdRouteImport.update({
  id: '/checkout/$courseId',
  path: '/checkout/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeacherRoute = AuthenticatedAppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClinicalCasesRoute =
  AuthenticatedAppClinicalCasesRouteImport.update({
    id: '/clinical-cases',
    path: '/clinical-cases',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiTutorRoute = AuthenticatedAppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAchievementsRoute =
  AuthenticatedAppAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoursesIndexRoute =
  AuthenticatedAppCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLessonsLessonIdRoute =
  AuthenticatedAppLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoursesCourseIdRoute =
  AuthenticatedAppCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai-tutor': typeof AuthenticatedAppAiTutorRoute
  '/app/clinical-cases': typeof AuthenticatedAppClinicalCasesRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/teacher': typeof AuthenticatedAppTeacherRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/courses/$courseId': typeof AuthenticatedAppCoursesCourseIdRoute
  '/app/lessons/$lessonId': typeof AuthenticatedAppLessonsLessonIdRoute
  '/app/courses/': typeof AuthenticatedAppCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai-tutor': typeof AuthenticatedAppAiTutorRoute
  '/app/clinical-cases': typeof AuthenticatedAppClinicalCasesRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/teacher': typeof AuthenticatedAppTeacherRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/courses/$courseId': typeof AuthenticatedAppCoursesCourseIdRoute
  '/app/lessons/$lessonId': typeof AuthenticatedAppLessonsLessonIdRoute
  '/app/courses': typeof AuthenticatedAppCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/_authenticated/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/ai-tutor': typeof AuthenticatedAppAiTutorRoute
  '/_authenticated/app/clinical-cases': typeof AuthenticatedAppClinicalCasesRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/app/teacher': typeof AuthenticatedAppTeacherRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/courses/$courseId': typeof AuthenticatedAppCoursesCourseIdRoute
  '/_authenticated/app/lessons/$lessonId': typeof AuthenticatedAppLessonsLessonIdRoute
  '/_authenticated/app/courses/': typeof AuthenticatedAppCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/checkout/$courseId'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-tutor'
    | '/app/clinical-cases'
    | '/app/community'
    | '/app/library'
    | '/app/teacher'
    | '/app/'
    | '/app/courses/$courseId'
    | '/app/lessons/$lessonId'
    | '/app/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/checkout/$courseId'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-tutor'
    | '/app/clinical-cases'
    | '/app/community'
    | '/app/library'
    | '/app/teacher'
    | '/app'
    | '/app/courses/$courseId'
    | '/app/lessons/$lessonId'
    | '/app/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app'
    | '/checkout/$courseId'
    | '/_authenticated/app/achievements'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ai-tutor'
    | '/_authenticated/app/clinical-cases'
    | '/_authenticated/app/community'
    | '/_authenticated/app/library'
    | '/_authenticated/app/teacher'
    | '/_authenticated/app/'
    | '/_authenticated/app/courses/$courseId'
    | '/_authenticated/app/lessons/$lessonId'
    | '/_authenticated/app/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CheckoutCourseIdRoute: typeof CheckoutCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$courseId': {
      id: '/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof CheckoutCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/teacher': {
      id: '/_authenticated/app/teacher'
      path: '/teacher'
      fullPath: '/app/teacher'
      preLoaderRoute: typeof AuthenticatedAppTeacherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/library': {
      id: '/_authenticated/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clinical-cases': {
      id: '/_authenticated/app/clinical-cases'
      path: '/clinical-cases'
      fullPath: '/app/clinical-cases'
      preLoaderRoute: typeof AuthenticatedAppClinicalCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai-tutor': {
      id: '/_authenticated/app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/app/ai-tutor'
      preLoaderRoute: typeof AuthenticatedAppAiTutorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/achievements': {
      id: '/_authenticated/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AuthenticatedAppAchievementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/courses/': {
      id: '/_authenticated/app/courses/'
      path: '/courses'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AuthenticatedAppCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lessons/$lessonId': {
      id: '/_authenticated/app/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/app/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedAppLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/courses/$courseId': {
      id: '/_authenticated/app/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAppCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAchievementsRoute: typeof AuthenticatedAppAchievementsRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAiTutorRoute: typeof AuthenticatedAppAiTutorRoute
  AuthenticatedAppClinicalCasesRoute: typeof AuthenticatedAppClinicalCasesRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppTeacherRoute: typeof AuthenticatedAppTeacherRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCoursesCourseIdRoute: typeof AuthenticatedAppCoursesCourseIdRoute
  AuthenticatedAppLessonsLessonIdRoute: typeof AuthenticatedAppLessonsLessonIdRoute
  AuthenticatedAppCoursesIndexRoute: typeof AuthenticatedAppCoursesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAchievementsRoute: AuthenticatedAppAchievementsRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAiTutorRoute: AuthenticatedAppAiTutorRoute,
  AuthenticatedAppClinicalCasesRoute: AuthenticatedAppClinicalCasesRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppTeacherRoute: AuthenticatedAppTeacherRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCoursesCourseIdRoute: AuthenticatedAppCoursesCourseIdRoute,
  AuthenticatedAppLessonsLessonIdRoute: AuthenticatedAppLessonsLessonIdRoute,
  AuthenticatedAppCoursesIndexRoute: AuthenticatedAppCoursesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CheckoutCourseIdRoute: CheckoutCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
